### PR TITLE
Support connecting to password protected faktory

### LINKED ISSUE #4: Add support for password protected faktory instances
Update the `HELLO` command to send the `pwdhash` field when faktory returns the iteration and salt fields in the `HI` response.

### PR DESCRIPTION
**Pull request by swelham**
Adds support for connecting to a password protected instance of a faktory server.

Fixes #4

### CODE REVIEW

**Comment by swelham** [comment]
Yeah we could start up another faktory instance during tests with the password set. Do you feel the unit test doesn't fully cover the functionality?

**Comment by john-griffin** [comment]
The unit tests look good and cover the detail of the protocol but there is currently no way to verify that it connects to real faktory with a password outside of running it.

**Comment by swelham** [comment]
Now updated with an integration test for both correct and incorrect password usage.

**Comment by john-griffin** [comment]
Thanks looks good, just working on the circle stuff

**Comment by john-griffin** [comment]
@SeatedInc/dev tests passing now, although its not possible to remap ports on docker containers in circle they can be mapped to different hostnames https://support.circleci.com/hc/en-us/articles/360007186173-Port-conflicts-with-service-containers-on-Docker-executor

Config is switched in test mode depending on if in CI mode.

**Pull request merged**
